name: Pipeline
on:
  push:
    branches: ['**']
jobs:
  lint:
    name: Lint with PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@2.1.2
        with:
          php-version: '7.2'
          coverage: none
          tools: prestissimo
      - name: Install dependencies
        run: |
          composer install \
            --ignore-platform-reqs \
            --prefer-dist \
            --no-ansi \
            --no-progress \
            --no-suggest
      - name: Lint with PHP_CodeSniffer
        run: vendor/bin/phpcs
  test:
    name: Test with PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
        lumen: ['^6.0', '^7.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@2.1.2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, gmp
          coverage: pcov
          tools: prestissimo
      - name: Install dependencies
        run: |
          rm -rf vendor/ composer.lock
          composer require --dev laravel/lumen-framework:${{ matrix.lumen }} \
            --optimize-autoloader \
            --prefer-dist \
            --no-ansi \
            --no-progress \
            --no-suggest
      - name: Test with PHPUnit
        run: |
          mkdir -p storage/artifacts/
          vendor/bin/phpunit \
            --testdox \
            --log-junit=storage/artifacts/phpunit-junit.xml \
            --coverage-clover=storage/artifacts/phpunit-coverage.xml \
            --coverage-text
#      - name: Upload coverage reports
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: coverage-reports
#          path: storage/artifacts
#  analyse:
#    name: Analyse with Sonar Scanner
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Unshallow
#        run: git checkout "${GITHUB_REF:11}"
#      - name: Download coverage reports
#        uses: actions/download-artifact@v1.0.0
#        with:
#          name: coverage-reports
#          path: storage/artifacts
#      - name: Setup sonar.properties
#        run: |
#          # Setup version
#          VERSION=$(jq -r .version composer.json)
#          echo "sonar.projectVersion=${VERSION}" >> sonar-project.properties
#
#          # Setup branches
#          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
#          if [[ "$CURRENT_BRANCH" = "dev" ]]; then
#            PARENT_BRANCH="master"
#          else
#            PARENT_BRANCH="dev"
#          fi
#
#          echo "sonar.branch.name=${CURRENT_BRANCH}" >> sonar-project.properties
#          echo "sonar.branch.target=${PARENT_BRANCH}" >> sonar-project.properties
#      - name: Analyse with Sonar Scanner
#        uses: mathrix-education/sonar-scanner@master
#        with:
#          version: 4.2.0.1873 # required
#          typescript: false
#          scan: true
#          args: -Dsonar.login=${{ secrets.SONAR_TOKEN }}
