name: Quality assessment
on: push
jobs:
  lint:
    name: Lint with PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@1.3.9
        with:
          php-version: 7.3
          extension-csv: mbstring, gmp
          coverage: pcov
      - name: Install dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Lint with PHP_CodeSniffer
        run: composer lint:details
  test:
    name: Test with PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@1.3.9
        with:
          php-version: 7.3
          extension-csv: mbstring, gmp
          coverage: pcov
      - name: Install dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Test with PHPUnit
        run: composer test:cover
      - name: Upload JUnit report
        uses: actions/upload-artifact@v1.0.0
        with:
          name: phpunit-junit.xml
          path: storage/artifacts/phpunit-junit.xml
      - name: Upload Clover coverage report
        uses: actions/upload-artifact@v1.0.0
        with:
          name: phpunit-coverage.xml
          path: storage/artifacts/phpunit-coverage.xml
  analyse:
    name: Analyse with Sonar Scanner
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Unshallow
        run: git checkout "${GITHUB_REF:11}"
      - name: Setup sonar.properties
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$CURRENT_BRANCH" = "dev" ]]; then
            PARENT_BRANCH="master"
          else
            PARENT_BRANCH="dev"
          fi
          echo "sonar.branch.name=${CURRENT_BRANCH}" >> sonar-project.properties
          echo "sonar.branch.target=${PARENT_BRANCH}" >> sonar-project.properties
      - name: Download JUnit report
        uses: actions/download-artifact@v1.0.0
        with:
          name: phpunit-junit.xml
          path: storage/artifacts
      - name: Download Clover coverage report
        uses: actions/download-artifact@v1.0.0
        with:
          name: phpunit-coverage.xml
          path: storage/artifacts
      - name: Patch Clover coverage report
        run: |
          sed -i 's/\/home\/runner\/work\/education-api\/education-api/\/github\/workspace/g' \
            storage/artifacts/phpunit-coverage.xml
      - name: Analyse with Sonar Scanner
        uses: docker://skilldlabs/sonar-scanner:3.3
        with:
          entrypoint: sonar-scanner
          args: -Dsonar.projectBaseDir=. -Dsonar.login=${{ secrets.SONAR_TOKEN }}
